# ######################################################################################################################
# AdvancedArmorStands Config
#
# Please do not delete anything in this file!
# For help please visit: https://github.com/Falyrion/AdvancedArmorStands
# ######################################################################################################################

# If true, armor stands will spawn with arms. If this config is set to `true`,
#   then the value of the next config `placeWithArms`  will be ignored
spawnWithArms: true

# If true, armor stands will be placed (by players) with arms.
placeWithArms: true

# If true, only the player who placed the armor stands can modify them. It applies only on armor stands that are placed
#  by a player while the ownershipOfPlacedArms is true
ownershipOfPlacedArmorStand: false

# The max range (blocks) in which armor stands can get effected by the plugins commands
commandEditRange: 100
