# ######################################################################################################################
#  AdvancedArmorStands Config
#  Please do not delete anything in this file!
#  For help please visit: https://github.com/Falyrion/AdvancedArmorStands
# ######################################################################################################################
#
# spawnWithArms:
# # If true, armor stands will spawn with arms. If this config is set to `true`, then the value of the next config `placeWithArms`  will be ignored
# # default spawnWithArms is true
#
# placeWithArms:
# # If true, armor stands will be placed (by players) with arms.
# # default  placeWithArms is true
#
# ownershipOfPlacedArmorStand:
# # If true, only the player who placed the armor stands can modify them. It applies only on armor stands that are placed by a player while the ownershipOfPlacedArms is true
# # default ownershipOfPlacedArmorStand is false
#
# commandEditRange
# # The max range (blocks) in which armor stands can get effected by the plugins commands
# # default commandEditRange is 100

spawnWithArms: true
placeWithArms: true
ownershipOfPlacedArmorStand: false
commandEditRange: 100
