# ######################################################################################################################
# Advanced Armor Stands Config
#
# Please do not delete anything in this file!
# For help visit https://github.com/Falyrion/AdvancedArmorStands
# ######################################################################################################################

# If true, armor stands will spawn with arms
spawnWithArms: true
