# ######################################################################################################################
# AdvancedArmorStands Config
#
# Please do not delete anything in this file!
# For help please visit: https://github.com/Falyrion/AdvancedArmorStands
# ######################################################################################################################

# If true, armor stands will spawn with arms
spawnWithArms: true

# The max range (blocks) in which armor stands can get effected by the plugins commands
commandEditRange: 100
